### ISSUE TITLE
Crash through dbgmsg

### ISSUE THREAD

**Issue by theKamikater** [matthewwall/weewx-wxt5x0#1]
I constantly keep getting this error message when trying to run WEEWX with the driver

Traceback (most recent call last):
  File "/usr/bin/weewxd", line 64, in <module>
    weewx.engine.main(options, args)
  File "/usr/share/weewx/weewx/engine.py", line 871, in main
    engine.run()
  File "/usr/share/weewx/weewx/engine.py", line 187, in run
    for packet in self.console.genLoopPackets():
  File "/usr/share/weewx/user/wxt5x0.py", line 446, in genLoopPackets
    logdbg("raw: %s" % raw)
  File "/usr/share/weewx/user/wxt5x0.py", line 88, in logdbg
    logmsg(syslog.LOG_DEBUG, msg)
  File "/usr/share/weewx/user/wxt5x0.py", line 85, in logmsg
    syslog.syslog(level, 'wxt5x0: %s' % msg)
TypeError: [priority,] message string

# 
Minicom log:
Welcome to minicom 2.7

OPTIONS: I18n 
Compiled on Apr 22 2017, 09:14:19.
Port /dev/ttyUSB0, 08:28:05

Press CTRL-A Z for help on special keys

0R0,Dm=000#,Sm=99.9#,Ta=23.7C,Ua=47.4P,Pa=951.1H,Rc=0.00M,Th=23.9C,Vh=0.0N
0R1,Dn=000#,Dm=000#,Dx=000#,Sn=0.0#,Sm=99.9#,Sx=0.0#
0R3,Rc=0.00M,Rd=0s,Ri=0.0M,Hc=0.0M,Hd=0s,Hi=0.0M
0R0,Dm=000#,Sm=99.9#,Ta=23.7C,Ua=47.4P,Pa=951.1H,Rc=0.00M,Th=23.9C,Vh=0.0N
0R0,Dm=000#,Sm=99.9#,Ta=23.7C,Ua=47.4P,Pa=951.1H,Rc=0.00M,Th=23.9C,Vh=0.0N
0
0R2,Ta=23.7C,Ua=47.4P,Pa=951.1H
0R0,Dm=000#,Sm=99.9#,Ta=23.7C,Ua=47.4P,Pa=951.1H,Rc=0.00M,Th=23.9C,Vh=0.0N
0
0R0,Dm=000#,Sm=99.9#,Ta=23.7C,Ua=47.4P,Pa=951.2H,Rc=0.00M,Th=23.9C,Vh=0.0N
0R1,Dn=000#,Dm=000#,Dx=000#,Sn=0.0#,Sm=99.9#,Sx=0.0#
0R3,Rc=0.00M,Rd=0s,Ri=0.0M,Hc=0.0M,Hd=0s,Hi=0.0M
0R0,Dm=000#,Sm=99.9#,Ta=23.7C,Ua=47.4P,Pa=951.2H,Rc=0.00M,Th=23.9C,Vh=0.0N
0R0,Dm=000#,Sm=99.9#,Ta=23.7C,Ua=47.4P,Pa=951.2H,Rc=0.00M,Th=23.9C,Vh=0.0N
0                                                                                                                                                        
0R2,Ta=23.7C,Ua=47.4P,Pa=951.2H                                                                                                                          
0R0,Dm=000#,Sm=99.9#,Ta=23.7C,Ua=47.4P,Pa=951.2H,Rc=0.00M,Th=23.9C,Vh=0.0N                                                                               
0R0,Dm=000#,Sm=99.9#,Ta=23.7C,Ua=47.4P,Pa=951.2H,Rc=0.00M,Th=23.9C,Vh=0.0N                                                                               
0                                                                                                                                                        
0R1,Dn=000#,Dm=000#,Dx=000#,Sn=0.0#,Sm=99.9#,Sx=0.0#                                                                                                     
0R3,Rc=0.00M,Rd=0s,Ri=0.0M,Hc=0.0M,Hd=0s,Hi=0.0M                                                                                                         
0R0,Dm=000#,Sm=99.9#,Ta=23.7C,Ua=47.4P,Pa=951.2H,Rc=0.00M,Th=23.9C,Vh=0.0N                                                                               
0R0,Dm=000#,Sm=99.9#,Ta=23.7C,Ua=47.4P,Pa=951.2H,Rc=0.00M,Th=23.9C,Vh=0.0N                                                                               
0R2,Ta=23.7C,Ua=47.4P,Pa=951.2H                                                                                                                          
0                                                                                                                                                        
0R0,Dm=000#,Sm=99.9#,Ta=23.7C,Ua=47.4P,Pa=951.2H,Rc=0.00M,Th=23.9C,Vh=0.0N                                                                               
0R0,Dm=000#,Sm=99.9#,Ta=23.7C,Ua=47.4P,Pa=951.2H,Rc=0.00M,Th=23.9C,Vh=0.0N                                                                               
0                                                                                                                                                        
0R1,Dn=000#,Dm=000#,Dx=000#,Sn=0.0#,Sm=99.9#,Sx=0.0#                                                                                                     
0R3,Rc=0.00M,Rd=0s,Ri=0.0M,Hc=0.0M,Hd=0s,Hi=0.0M                                                                                                         
0R0,Dm=000#,Sm=99.9#,Ta=23.7C,Ua=47.4P,Pa=951.2H,Rc=0.00M,Th=23.9C,Vh=0.0N                                                                               
0R0,Dm=000#,Sm=99.9#,Ta=23.7C,Ua=47.4P,Pa=951.2H,Rc=0.00M,Th=24.0C,Vh=0.0N                                                                               
0R2,Ta=23.7C,Ua=47.4P,Pa=951.2H                                                                                                                          
0R0,Dm=000#,Sm=99.9#,Ta=23.7C,Ua=47.4P,Pa=951.2H,Rc=0.00M,Th=23.9C,Vh=0.0N                                                                               
0                                                                                                                                                        
0R0,Dm=000#,Sm=99.9#,Ta=23.7C,Ua=47.4P,Pa=951.2H,Rc=0.00M,Th=23.9C,Vh=0.0N                                                                               
0R1,Dn=000#,Dm=000#,Dx=000#,Sn=0.0#,Sm=99.9#,Sx=0.0#                                                                                                     
0R3,Rc=0.00M,Rd=0s,Ri=0.0M,Hc=0.0M,Hd=0s,Hi=0.0M                                                                                                         
0R0,Dm=000#,Sm=99.9#,Ta=23.7C,Ua=47.4P,Pa=951.2H,Rc=0.00M,Th=23.9C,Vh=0.0N                                                                               
0R0,Dm=000#,Sm=99.9#,Ta=23.7C,Ua=47.4P,Pa=951.2H,Rc=0.00M,Th=23.9C,Vh=0.0N                                                                               
0                                                                                                                                                        
0R2,Ta=23.7C,Ua=47.4P,Pa=951.2H                                                                                                                          
0R0,Dm=000#,Sm=99.9#,Ta=23.7C,Ua=47.3P,Pa=951.2H,Rc=0.00M,Th=24.0C,Vh=0.0N                                                                               
0                                                                                                                                                        
0R0,Dm=000#,Sm=99.9#,Ta=23.7C,Ua=47.3P,Pa=951.2H,Rc=0.00M,Th=23.9C,Vh=0.0N                                                                               
0R1,Dn=000#,Dm=000#,Dx=000#,Sn=0.0#,Sm=99.9#,Sx=0.0#                                                                                                     
0R3,Rc=0.00M,Rd=0s,Ri=0.0M,Hc=0.0M,Hd=0s,Hi=0.0M                                                                                                         
0R0,Dm=000#,Sm=99.9#,Ta=23.7C,Ua=47.3P,Pa=951.2H,Rc=0.00M,Th=23.9C,Vh=0.0N                                                                               
0R0,Dm=000#,Sm=99.9#,Ta=23.7C,Ua=47.3P,Pa=951.2H,Rc=0.00M,Th=23.9C,Vh=0.0N                                                                               
0                                                                                                                                                        
0R2,Ta=23.7C,Ua=47.3P,Pa=951.2H

**Comment by matthewwall** [comment]
fixed at commit #a9e80bf
