### ISSUE TITLE
Need Communication parameters.

### ISSUE THREAD

**Issue by Vyachep** [matthewwall/weewx-wxt5x0#3]
Please help.
How to set new hardware (wxt520) for working?
I need to know speed, parity, crc on/off and all communication parameters. 
I use RS485 USB converter with 2 wires.
Thanks.

**Comment by matthewwall** [comment]
this driver currently supports only the ASCII communication mode.  the serial settings for that are:

RS422 NMEA defaults to 4800, 8, N, 1
