### ISSUE TITLE
Does driver require USB connection

### ISSUE THREAD

**Issue by aterhorst** [matthewwall/weewx-wxt5x0#7]
I have inherited a WXT520 with M12 connector cable that was wired up to a Campbell Scientific logger. The USB data cable is incredibly expensive. I assume your driver expects a USB connection?

**Comment by matthewwall** [comment]
the driver is written to handle serial, nmea, and sdi12 protocols

the driver defaults to 'serial' talking to '/dev/ttyUSB0', but if you have a direct serial connection instead of a usb-serial adapter, that should work.  just specify the serial device.
